Update after

diff --git a/after b/after
--- a/after
+++ b/after
@@ -13,3 +13,21 @@ bulk_insert_to_vertica() {
         fi
     fi
 }
+
+
+
+
+# Function to insert rejected lines into the Vertica table
+bulk_insert_to_vertica() {
+    invalid_file="okfile/invalid_$(basename "$FULLFILENAME")"
+    if [[ $vertica_flag -eq 1 && -s "$invalid_file" ]]; then
+        echo "Inserting rejected lines into Vertica..."
+        ${GpVsql}vsql -h ${GsDWHbaseHostsql} -B ${backup} -U ${GsDWHbaseUser} -w ${GsDWHbasepswd} -t -c "COPY $GsDWHbaseSchema.T_APP_REJ_ODS_GLOBAL(LB_COLUMN, DT_DREJET) FROM LOCAL '$invalid_file' DELIMITER E'$custom_delimiter' ENFORCELENGTH DIRECT;"
+        if [[ $? -eq 0 ]]; then  # Check if the COPY command was successful
+            echo "Insertion complete."
+        else
+            echo "Error during COPY operation."
+            # No need for rollback, Vertica handles it in case of COPY failure.
+        fi
+    fi
+}
